version: '3.4'

services:
  db:
    container_name: 'schedule_db'
    image: mariadb:10.11.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "33006:3306"
    volumes:
      - ./containers/mysql_data:/var/lib/mysql
    command: --innodb-use-native-aio=0
  nginx:
    container_name: 'schedule_nginx'
    build: ./containers/nginx
    command: >
      /bin/bash -c
      "envsubst '$$NGINX_SERVER_NAME $$NGINX_SERVER_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    environment:
      - TZ=Asia/Tokyo
      - NGINX_SERVER_NAME=localhost
      - NGINX_SERVER_PORT=80
    ports:
      - 80:80
      - 443:443
    volumes:
      - tmp:/app/tmp
      - public:/app/public
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ASSETS_PRECOMPILE: 'false'
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: schedule_development
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - tmp:/app/tmp
      - public:/app/public
    links:
      - db
volumes:
  mysql_data:
  bundle:
  tmp:
  public:
